In [19]:
import numpy as np # library to handle data in a vectorized manner
import pandas as pd # library for data analsysis
import requests 
from bs4 import BeautifulSoup 


print('Libraries imported.')

Libraries imported.

In [20]:
source  = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

In [21]:
soup = BeautifulSoup(source,'lxml')

In [22]:
stat = soup.find('table', class_ ="wikitable sortable")

In [23]:
len(stat)

2

In [24]:
tr1 = stat.find_all('tr')

In [25]:
final = []
for row in tr1:
    cols=row.find_all('td')
    cols=[x.text.strip() for x in cols]
    #print(cols + ",")
    final = final + cols

In [26]:
s = [final[i:i+3] for i in range(0,len(final),3)]

In [27]:
d1 = pd.DataFrame()
d1['Postal Code'] = s
d1.head()

                                         Postal Code
0                  [M1A, Not assigned, Not assigned]
1                  [M2A, Not assigned, Not assigned]
2                       [M3A, North York, Parkwoods]
3                [M4A, North York, Victoria Village]
4  [M5A, Downtown Toronto, Regent Park, Harbourfr...

In [28]:
d1.shape

(180, 1)

In [29]:
k = 0
for i in range(0,180):
        for j in range(0,1):
 #          print(j)
 #          print(final[k] + "," + final[k+1] + "," + final[k+2])
            d1['Postal Code'][i] = final[k] + "," + final[k+1] + "," + final[k+2]
            k = k + 3
            
         
d1.tail()

                                           Postal Code
175                      M5Z,Not assigned,Not assigned
176                      M6Z,Not assigned,Not assigned
177                      M7Z,Not assigned,Not assigned
178  M8Z,Etobicoke,Mimico NW, The Queensway West, S...
179                      M9Z,Not assigned,Not assigned

In [30]:
new = d1["Postal Code"].str.split(",", n = 2, expand = True) 
d1["a"]= new[0] 
d1["b"]= new[1] 
d1["c"]= new[2]
d1.head()

,Postal Code,a,b,c
0,"M1A,Not assigned,Not assigned",M1A,Not assigned,Not assigned
1,"M2A,Not assigned,Not assigned",M2A,Not assigned,Not assigned
2,"M3A,North York,Parkwoods",M3A,North York,Parkwoods
3,"M4A,North York,Victoria Village",M4A,North York,Victoria Village
4,"M5A,Downtown Toronto,Regent Park, Harbourfront",M5A,Downtown Toronto,"Regent Park, Harbourfront"

In [31]:
d1 = d1.drop(['Postal Code'],axis=1)

In [32]:
d1.columns = ["Postal Code","Borough","Neighbourhood"]

In [33]:
d1.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [34]:
d1 = d1[d1['Borough'] != 'Not assigned']

In [35]:
d1.shape

(103, 3)

In [36]:
cnt = 0 
for i in range(0,103):
    j = 2
    if d1.iloc[i][j] == 'Not assigned':
        d1.iloc[i][j] = d1.iloc[i][j-1]
        j = j + 1

In [37]:
d1.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [40]:
df = d1.reset_index()

In [41]:
df.head(20)

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
6,M1B,Scarborough,"Malvern, Rouge"
7,M3B,North York,Don Mills
8,M4B,East York,"Parkview Hill, Woodbine Gardens"
9,M5B,Downtown Toronto,"Garden District, Ryerson"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
13,M3C,North York,Don Mills
14,M4C,East York,Woodbine Heights
15,M5C,Downtown Toronto,St. James Town
16,M6C,York,Humewood-Cedarvale
17,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
18,M1E,Scarborough,"Guildwood, Morningside, West Hill"
19,M4E,East Toronto,The Beaches

In [42]:
df1 = df.sort_values('Postal Code',ascending=True)

In [45]:
df.head()

  Postal Code           Borough                                Neighbourhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [44]:
df.shape

(103, 3)